dist: xenial
language: node_js
branches:
  only:
    - master
node_js:
  - "12.14.1"
addons:
  apt:
    packages:
      - libavahi-compat-libdnssd-dev
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
  - npx browserslist@latest --update-db # update browserslist browser versions
jobs:
  include:
    - stage: lint
      script: npm run lint -- --max-warnings 0 && npm run sass-lint -- --max-warnings 0
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build:electron
