os:
  - osx
language: node_js
node_js:
  - "6.9"
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
