language: node_js
branches:
  only:
    - master
node_js:
  - "8.11"
cache:
  directories:
    - node_modules # NPM packages
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libavahi-compat-libdnssd-dev -y
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run lint && npm run sass-lint && npm run test && npm run build
    - script: npm run generate-schema &&
              npm run validate-protocol &&
              npm run validate-protocol ./public/protocols/teaching-protocol.netcanvas/protocol.json
