dist: xenial
language: node_js
branches:
  only:
    - master
node_js:
  - "12.14.1"
cache:
  directories:
    - node_modules # NPM packages

install:
  - npm install
jobs:
  include:
    - stage: lint
      script: npm run lint -- --max-warnings 0 &&
      npm run sass-lint -- --max-warnings 0
    - stage: test
      script: npm run test
    - stage: build (Electron)
      script: npm run build:electron


