language: node_js
branches:
  only:
    - master
node_js:
  - "8.11"
cache:
  directories:
    - node_modules # NPM packages
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libavahi-compat-libdnssd-dev -y
install:
  - npm install
jobs:
  include:
    - stage: prebuild
      script: npm run test
    - script: npm run lint
    - script: npm run sass-lint
    - stage: build
      script: npm run build
